parameters:
#    hello_di_accounting.example.class: HelloDi\AccountingBundle\Example

services:
#    hello_di_accounting.example:
#        class: %hello_di_accounting.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    accounting:
        class: HelloDi\AccountingBundle\Controller\DefaultController
        arguments: [@doctrine.orm.default_entity_manager]
