parameters:
#    hello_di_core.example.class: HelloDi\CoreBundle\Example

services:
#    hello_di_core.example:
#        class: %hello_di_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
