parameters:

services:
    record_exception:
        class: HelloDi\CoreBundle\Listener\Exception
        arguments: [@doctrine.orm.default_entity_manager,@session]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onWriteException }

    authentication_handler:
        class: HelloDi\CoreBundle\Listener\AuthenticationHandler
        arguments: [@router, @security.context]

    locale_listener:
        class: HelloDi\CoreBundle\Listener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest}
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin}

    notification_handler:
        class:  HelloDi\CoreBundle\Listener\Notificationhandler
        arguments: [@doctrine.orm.default_entity_manager,@security.context]

    calc_vat_formula:
        class: HelloDi\CoreBundle\Listener\CalcVatFormula
        arguments: [%VatFormula%]

    account_currency:
        class: HelloDi\CoreBundle\Listener\AccountCurrency
        arguments: [@doctrine.orm.default_entity_manager]