hello_di_pricing_model_index:
    pattern:  /
    defaults: { _controller: HelloDiPricingBundle:Model:indexModel }

hello_di_pricing_model_add:
    pattern: /add
    defaults: { _controller: HelloDiPricingBundle:Model:NewDistributorModel }

hello_di_pricing_model_edit:
    pattern: /{id}/edit
    defaults: { _controller: HelloDiPricingBundle:Model:EditDistributorModel }
