fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
    path: /profile
    defaults: { _controller: FOSUserBundle:Profile:edit}
    requirements: { _method: GET }

fos_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit}

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"