hello_di_di_distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /app

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /app/user/profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /app/user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /app/user

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
#    prefix: /_gcb