hello_di_core:
    resource: "@HelloDiCoreBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_retailer:
    resource: "@HelloDiRetailerBundle/Resources/config/routing.yml"
    prefix:   /app/r

hello_di_distributor:
    resource: "@HelloDiDistributorBundle/Resources/config/routing.yml"
    prefix:   /app/d

hello_di_master:
    resource: "@HelloDiMasterBundle/Resources/config/routing.yml"
    prefix:   /app/m

hello_di_pricing:
    resource: "@HelloDiPricingBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_accounting:
    resource: "@HelloDiAccountingBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_aggregator:
    resource: "@HelloDiAggregatorBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_di_distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing.yml"
    prefix:   /_old_/

hello_di_user:
    resource: "@HelloDiUserBundle/Resources/config/routing.yml"
    prefix:   /app

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
#    prefix: /_gcb