hello_di_core:
    resource: "@HelloDiCoreBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_retailer:
    resource: "@HelloDiRetailerBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_distributor:
    resource: "@HelloDiDistributorBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_master:
    resource: "@HelloDiMasterBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_pricing:
    resource: "@HelloDiPricingBundle/Resources/config/routing.yml"
    prefix:   /pricing

hello_di_user:
    resource: "@HelloDiUserBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_accounting:
    resource: "@HelloDiAccountingBundle/Resources/config/routing.yml"
    prefix:   /

hello_di_di_distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /app

fos_user_profile_show:
    path: /app/user/profile
    defaults: { _controller: FOSUserBundle:Profile:edit}
    requirements: { _method: GET }

fos_user_profile_edit:
    path: /app/user/profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit}

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /app/user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /app/user

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

#gregwar_captcha_routing:
#    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
#    prefix: /_gcb