security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: authentication_handler
            logout:
                target: fos_user_security_login
                path: fos_user_security_logout
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_USER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app/m/admin, roles: ROLE_MASTER_ADMIN }
        - { path: ^/app/m, roles: ROLE_MASTER }
        - { path: ^/app/d/admin, roles: ROLE_DISTRIBUTOR_ADMIN }
        - { path: ^/app/d, roles: ROLE_DISTRIBUTOR }
        - { path: ^/app/r/admin, roles: ROLE_RETAILER_ADMIN }
        - { path: ^/app/r, roles: ROLE_RETAILER }

    role_hierarchy:
        ROLE_RETAILER_ADMIN: ROLE_RETAILER
        ROLE_DISTRIBUTOR_ADMIN: ROLE_DISTRIBUTOR
        ROLE_MASTER_ADMIN: ROLE_MASTER