hello_di_distributor_retailer_index:
    pattern:  /
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:index"}

hello_di_distributor_retailer_add:
    pattern:  /add
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:add"}

#transaction
hello_di_distributor_retailer_transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:transaction"}

hello_di_distributor_retailer_transaction_funding:
    pattern:  /{id}/transactions/funding
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:funding"}

#items
hello_di_distributor_retailer_item:
    pattern:  /{id}/items
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:item" }

#users
hello_di_distributor_retailer_user:
    pattern:  /{id}/users
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:user" }

hello_di_distributor_retailer_user_add:
    pattern:  /{id}/users/add
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:userAdd" }

hello_di_distributor_retailer_user_edit:
    pattern:  /{id}/users/{user_id}/edit
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:userEdit" }

#info
hello_di_distributor_retailer_info:
    pattern:  /{id}/info
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:info" }

#entity
hello_di_distributor_retailer_entity:
    pattern:  /{id}/entity
    defaults: { _controller: "HelloDiDistributorBundle:Retailer:entity" }
