hello_di_distributor_setting_profile:
    pattern:  /profile
    defaults: { _controller: "HelloDiDistributorBundle:Setting:profile" }

hello_di_distributor_setting_staff_index:
    pattern:  /staff
    defaults: { _controller: "HelloDiDistributorBundle:Setting:staff" }

hello_di_distributor_setting_staff_add:
    pattern:  /staff/add
    defaults: { _controller: "HelloDiDistributorBundle:Setting:staffAdd" }

hello_di_distributor_setting_staff_edit:
    pattern:  /staff/{user_id}/edit
    defaults: { _controller: "HelloDiDistributorBundle:Setting:staffEdit" }