Retailer_Items_Show:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ShowItems }

Retailer_Items_Change_Favorite:
    pattern:  /changeFavorite/{priceid}/
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:SwitchFavoriteItem }