RetailerShowNotification:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ShowNotification }

RetailerReadNotification:
    pattern:  /read
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ReadNotification }