Retailer_Shop_buy_Imtu:
    pattern:  /buyImtu
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:BuyImtu }
    requirements: { _method: post }

Retailer_Shop_buy:
    pattern:  /buy
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Buy }
    requirements: { _method: post }

Retailer_Shop_dmtu:
    pattern:  /dmtu
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Dmtu }

Retailer_Shop_callingCard:
    pattern:  /calling-cards
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:CallingCard }

Retailer_Shop_e-payment:
    pattern:  /e-payment
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Epayment }

Retailer_Shop_imtu:
    pattern:  /imtu
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Imtu }

Retailer_Shop_favourite:
    pattern:  /favourites
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Favourites }

Retailer_Shop_print:
    pattern:  /print/{print}/
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Print , print: 'web' }

Retailer_Shop_Error_print:
    pattern:  /Error
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ErrorOnPrint }

Retailer_Shop_Read_Number_imtu:
    pattern:  /readNumber
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:readNumber }

Retailer_Shop_Get_Prices_imtu:
    pattern:  /getPricesImtu
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:getPrices }

Retailer_Shop_imtu_print:
    pattern:  /printimtu/{id}/{print}/
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:PrintImtu , print: 'web' }