RetailerTickets:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:tickets }

RetailerTicketsNote:
    pattern:  /{id}/notes
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsnote }

RetailerTicketsClose:
    pattern:  /{id}/close
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsclose }

RetailerTicketsNew:
    pattern:  /new/{data}/
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsnew,data:1}

RetailerTicketsChangeStatus:
    pattern:  /{id}/change/status
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketschangestatus }

RetailerTicketsStatus:
    pattern:  /{id}/change/
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsstatus }