ShowMyAccountProv:
    pattern:  /providers
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ShowMyAccountProv" }

ManageProv:
    pattern:  /providers/Manageprov/{id}/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageProv" }

EditAccountProv:
    pattern:  /providers/Info
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditAccountProv" }

EditAccountProvSubmit:
    pattern:  /providers/Manageprovsubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditAccountProvSubmit" }

ManageProvEntiti:
    pattern:  /providers/Entiti
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageProvEntiti" }

AddAccountProvMaster:
    pattern:  /providers/select/entity
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountProvMaster" }


AddAccountProveMaster2Step:
    pattern:  /providers/entity/new
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountProveMaster2Step" }

AddAccountProvMasterOk:
    pattern:  /providers/{id}/new
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountProvMasterOk" }


#ChangeAdminProvAccountOk:
#    pattern:  /providers/{iduser}/{idacc}/Change/UserPrivilegeProvOk
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ChangeAdminProvAccountOk" }

ProvTransfer:
    pattern:  /providers/{id}/transaction/transfer
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ProvTransfer" }

ProvRegister:
    pattern:  /providers/{id}/transaction/register
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:Provregister" }
#-------------------

ShowMyAccountDist:
    pattern:  distributors/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ShowMyAccountDist" }

AddAccountDistMaster:
    pattern:  distributors/Add/AccountDist
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountDistMaster" }

ManageDist:
    pattern:  distributors/ManageDist/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDist" }

ManageDistInfo:
    pattern:  distributors/Info
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistInfo" }

ManageDistInfoEdit:
    pattern:  distributors/ManageDistInfo/Edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistInfoEdit" }

#ManageDistTransaction:
#    pattern:  distributors/subaccounts
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistTransaction" }

ManageDistChildren:
    pattern:  distributors/subaccounts
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistChildren"}
DistChildrenCreate:
    pattern:  distributors/ManageDistChildren/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistChildren"}
ManageDistUser:
    pattern:  distributors/User/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistUser" }
ManageDistUserSearch:
    pattern:  distributors/Search/ManageDistUser/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistUserSearch" }
DistUserPrivilege:
    pattern:  Account/{idacc}/User/{iduser}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DistUserPrivilege" }
ManageDistUserSearchReset:
    pattern:  reset/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistUserSearchReset" }
AccountDistChildrenSearch:
    pattern:  distributors/{id}/SearchDistChildren
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AccountDistChildrenSearch"}
ManageDistSettings:
    pattern:  distributors/Settings
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistSettings"}
ManageDistSettingsSubmit:
    pattern:  distributors/Edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistSettingsSubmit"}

MasterDistTransaction:
    pattern:  distributors/{id}/transactions
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DistTransaction"}
DetailsMasterDistTransaction:
    pattern:  distributors/{id}/transactions/details
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DetailsTransaction"}
MasterDistSale:
    pattern:  distributors/reports/{id}/sales
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:Sale"}
MasterDistDetailsSale:
    pattern:  distributors/reports/sales/{id}/detailes
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DetailsSale"}

MasterDistFunding:
    pattern:  distributors/{id}/transactions/funding
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:Funding"}

MasterDistApplayFunding:
    pattern:  distributors/{id}/transactions/funding/applay
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:FundingApplay"}

MasterDistUpdateFunding:
    pattern:  distributors/{id}/transactions/funding/update
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:FundingUpdate"}
MasterDistPurchases:
    pattern:  distributors/{id}/purchases
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:Purchases"}

#---- items prov
ManageItemsProv:
    pattern:  /providers/Items
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageItemsProv" }

AddItemProv:
    pattern:  /providers/Items/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemProv" }

AddItemProvSubmit:
    pattern:  /providers/Items/addSubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemProvSubmit" }

EditItemProv:
    pattern:  /providers/Items/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemProv" }

EditItemProvSubmit:
    pattern:  /providers/Items/editSubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemProvSubmit" }

#---- items dist
ManageItemsDist:
    pattern:  /distributors/Items
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageItemsDist" }

AddItemDist:
    pattern:  /distributors/Items/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemDist" }

AddItemDistSubmit:
    pattern:  /distributors/Items/addSubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemDistSubmit" }

EditItemDist:
    pattern:  /distributors/Items/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemDist" }

EditItemDistSubmit:
    pattern:  /distributors/Items/editSubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemDistSubmit" }

#---- inputs prov
ManageInputsProv:
    pattern:  /providers/Inputs
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageInputsProv" }

UploadInputProv:
    pattern:  /providers/Inputs/Upload
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProv" }

UploadInputProvSubmit:
    pattern:  /providers/Inputs/UploadSubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmit" }

UploadInputProvSubmitAccepted:
    pattern:  /providers/Inputs/UploadSubmitAccepted
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmitAccepted" }

UploadInputProvSubmitCanceled:
    pattern:  /providers/Inputs/UploadSubmitCanceled
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmitCanceled" }
#-------Retailers--------------#
ListUsersInRetailers:
    pattern:  /retailers/{id}/users
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:ListUsersInRetailers" }

#------strat kamal transaction Root-----#
MasterProvTransaction:
    pattern:  /providers/{id}/transactions
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:MasterProvTransaction" }

MasterProvRemoved:
    pattern:  /providers/{id}/removed
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:MasterProvRemoved" }


#------End kamal transaction Root-----#