code:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Code:index" }

code_history:
    pattern:  /{id}/history
    defaults: { _controller: "HelloDiDiDistributorsBundle:Code:history" }