Ent_Main:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ListEntities" }

Ent_Index:
    pattern:  /index/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:index" }

Ent_Accounts:
    pattern:  /accounts
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:accounts" }
Ent_Address:
    pattern:  /{id}/address
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:address" }

Ent_Edit_Address:
    pattern:  /address/{id}/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:editaddress" }

Ent_Users:
    pattern:  /users
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:users" }

Ent_Info:
    pattern:  /info
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:info" }

Ent_InfoSubmit:
    pattern:  /entities/info/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:infoSubmit" }

AddNewUserEntiti:
    pattern:  /entities/{id}/user/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:AddNewUserEntiti" }

EditUserEntities:
    pattern:  /entities/user/{id}/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:EditUserEntities" }

ChangeRoleUserEntities:
    pattern:  /entities/user/{id}/roleedit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ChangeRoleUserEntities" }

AddProv:
    pattern:  /entities/{id}/new/provoder
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:AddProv"}

AddDist:
    pattern:  /entities/{id}/new/distibutors
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:AddDist"}
ProvTransaction:
    pattern:  /provider/{id}/transaction
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ProvTransaction"}
DistTransaction:
    pattern:  /distributors/{id}/transaction
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ProvTransaction"}