item:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:index" }

item_new:
    pattern:  /new
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:new" }

item_show:
    pattern:  /{id}/details
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:show" }

item_edit:
    pattern:  /{id}/details/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:edit" }

#description
item_desc:
    pattern:  /{id}/description
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descIndex" }

item_desc_new:
    pattern:  /{id}/description/new
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descNew" }

item_desc_edit:
    pattern:  /{id}/description/{descid}/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descEdit" }

item_desc_update:
    pattern:  /{id}/description/{descid}/update
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descUpdate" }
