item:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:index" }

item_new:
    pattern:  /add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:new" }

item_show:
    pattern:  /{id}/details
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:show" }

item_edit:
    pattern:  /{id}/details/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:edit" }

item_price:
    pattern:  /{id}/item-per-distributors
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:ItemPerDist" }

#description
item_desc:
    pattern:  /{id}/descriptions
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descIndex" }

item_desc_new:
    pattern:  /{id}/descriptions/new
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descNew" }

item_desc_edit:
    pattern:  /{id}/descriptions/{descid}/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:descEdit" }
