TestLog:
    path: /{flag}/
    defaults: { _controller: 'HelloDiDiDistributorsBundle:Default:Log','flag':null}
    requirements:
        flag: Export|DeleteAll|DeleteSearch|null

DeleteLog:
    path: /log/delete
    defaults: { _controller: 'HelloDiDiDistributorsBundle:Default:DeleteLog'}
