MasterShowNotification:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Account:ShowNotification }

MasterReadNotification:
    pattern:  /read/notification
    defaults: { _controller: HelloDiDiDistributorsBundle:Account:ReadNotification }