MasterStaff:
    pattern:  /staff
    defaults: { _controller: "HelloDiDiDistributorsBundle:Setting:staff" }

MasterStaffAdd:
    pattern:  /staff/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Setting:staffadd" }

MasterStaffEdit:
    pattern:  /staff/{id}/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Setting:staffedit"}
