distributor_transactions_new:
    pattern:  /new
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:new}

distributor_transactions_validate:
    pattern:  /{id}/validate
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:validate}

distributor_transactions_result:
    pattern:  /result
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:result}

distributor_index:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:dashboard}

distributor_transactions_ogone_template:
    path:   /ogone-template
    defaults:
        _controller: FrameworkBundle:Template:template
        template: HelloDiDiDistributorsBundle:Ogone:EpaymentTemplate.html.twig
