retailer_transactions_new:
    pattern:  /new
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:new}

retailer_transactions_validate:
    pattern:  /{id}/validate
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:validate}

retailer_transactions_result:
    pattern:  /result
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:result}

retailer_index:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:dashboard}
retailer_transactions_ogone_template:
    path: /ogone-template
    defaults:
        template: 'HelloDiDiDistributorsBundle:Ogone:EpaymentTemplate'
