hello_di_master_code_index:
    pattern:  /
    defaults: { _controller: "HelloDiMasterBundle:Code:index" }

hello_di_master_code_search:
    pattern:  /search
    defaults: { _controller: "HelloDiMasterBundle:Code:search" }

hello_di_master_code_history:
    pattern:  /{id}/history
    defaults: { _controller: "HelloDiMasterBundle:Code:history" }

hello_di_master_code_dead_beat:
    pattern:  /dead_beat
    defaults: { _controller: "HelloDiMasterBundle:Code:DeadBeat" }
    methods: post

hello_di_master_code_credit_note:
    pattern:  /credit_note
    defaults: { _controller: "HelloDiMasterBundle:Code:CreditNote" }
    methods: post

hello_di_master_code_credit_note_and_dead_beat:
    pattern:  /{id}/credit_note_and_deat_beat
    defaults: { _controller: "HelloDiMasterBundle:Code:CreditNoteAndDeadBeat" }