hello_di_master_distributor_index:
    pattern:  /
    defaults: { _controller: "HelloDiMasterBundle:Distributor:index" }

hello_di_master_distributor_add:
    pattern:  /add
    defaults: { _controller: "HelloDiMasterBundle:Distributor:add" }

#transactions
hello_di_master_distributor_transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: "HelloDiMasterBundle:Distributor:transactions"}

hello_di_master_distributor_transaction_funding:
    pattern:  /{id}/transactions/funding
    defaults: { _controller: "HelloDiMasterBundle:Distributor:funding"}

#purchases
hello_di_master_distributor_purchases:
    pattern:  /{id}/purchases
    defaults: { _controller: "HelloDiMasterBundle:Distributor:purchases"}

#users
hello_di_master_distributor_users:
    pattern:  /{id}/users
    defaults: { _controller: "HelloDiMasterBundle:Distributor:users" }

hello_di_master_distributor_users_add:
    pattern:  /{id}/users/add
    defaults: { _controller: "HelloDiMasterBundle:Distributor:usersAdd" }

hello_di_master_distributor_users_edit:
    pattern:  /{id}/users/{user_id}
    defaults: { _controller: "HelloDiMasterBundle:Distributor:usersEdit"}

#info
hello_di_master_distributor_info:
    pattern:  /{id}/info
    defaults: { _controller: "HelloDiMasterBundle:Distributor:info"}

#entity
hello_di_master_distributor_entity:
    pattern:  /{id}/entity
    defaults: { _controller: "HelloDiMasterBundle:Distributor:entity" }

#LoadActionDist:
#    pattern:  /loaddist
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:LoadActionDist" }
#
#DetailsMasterDistTransaction:
#    pattern:  /{id}/transactions/{tranid}/details
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DetailsTransaction"}
#
##sales---------------------
#MasterDistSale:
#    pattern:  /{id}/sales
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:Sale"}
#
#MasterDistDetailsSale:
#    pattern:  /sales/details
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DetailsSale"}