hello_di_master_provider_index:
    pattern:  /
    defaults: { _controller: "HelloDiMasterBundle:Provider:index" }

hello_di_master_provider_add:
    pattern:  /add
    defaults: { _controller: "HelloDiMasterBundle:Provider:add" }

#transactions
hello_di_master_provider_transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: "HelloDiMasterBundle:Provider:transactions" }

hello_di_master_provider_transaction_register:
    pattern:  /{id}/transactions/register
    defaults: { _controller: "HelloDiMasterBundle:Provider:transactionRegister" }

hello_di_master_provider_transaction_transfer:
    pattern:  /{id}/transactions/transfer
    defaults: { _controller: "HelloDiMasterBundle:Provider:transactionTransfer" }

#items
hello_di_master_provider_items:
    pattern:  /{id}/items
    defaults: { _controller: "HelloDiMasterBundle:Provider:items" }

hello_di_master_provider_items_upload:
    pattern:  /{id}/items/{price_id}/upload
    defaults: { _controller: "HelloDiMasterBundle:Provider:upload" }

hello_di_master_provider_items_upload_accepted:
    pattern:  /{id}/items/{price_id}/upload/accept
    defaults: { _controller: "HelloDiMasterBundle:Provider:uploadAccepted" }

#inputs
hello_di_master_provider_inputs:
    pattern:  /{id}/inputs
    defaults: { _controller: "HelloDiMasterBundle:Provider:inputs" }

#removed
hello_di_master_provider_removed:
    pattern:  /{id}/removed
    defaults: { _controller: "HelloDiMasterBundle:Provider:removed" }

#info
hello_di_master_provider_info:
    pattern:  /{id}/info
    defaults: { _controller: "HelloDiMasterBundle:Provider:info" }

#entity
hello_di_master_provider_entity:
    pattern:  /{id}/entity
    defaults: { _controller: "HelloDiMasterBundle:Provider:entity" }
