hello_di_master_provider_index:
    pattern:  /
    defaults: { _controller: "HelloDiMasterBundle:Provider:index" }

hello_di_master_provider_add:
    pattern:  /add
    defaults: { _controller: "HelloDiMasterBundle:Provider:add" }

#transactions
hello_di_master_provider_transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: "HelloDiMasterBundle:Provider:transactions" }

hello_di_master_provider_transaction_register:
    pattern:  /{id}/transactions/register
    defaults: { _controller: "HelloDiMasterBundle:Provider:transactionRegister" }

hello_di_master_provider_transaction_transfer:
    pattern:  /{id}/transactions/transfer
    defaults: { _controller: "HelloDiMasterBundle:Provider:transactionTransfer" }

#items
hello_di_master_provider_items:
    pattern:  /{id}/items
    defaults: { _controller: "HelloDiMasterBundle:Provider:items" }

#LoadActionProv:
#    pattern:  /loadprov
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:LoadActionProv" }
#
#ProvTransfer:
#    pattern:  /{id}/transactions/transfer
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ProvTransfer" }
#
#MasterProvTransactionDetails:
#    pattern:  /{id}/transactions/{tranid}/details
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:MasterProvTransactionDetails" }
#
#MasterProvTransactionDelete:
#    pattern:  /{id}/transactions/{tranid}/delete
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:MasterProvTransactionDelete" }
#
##items---------------------
#ManageItemsProv:
#    pattern:  /{id}/items
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageItemsProv" }
#
#AddItemProv:
#    pattern:  /{id}/items/add
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemProv" }
#
#EditItemProv:
#    pattern:  /{id}/items/{itemid}/edit
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemProv" }
#
#UploadInputProv:
#    pattern:  /{id}/items/{itemid}/upload
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProv" }
#
#UploadInputProvSubmit:
#    pattern:  /{id}/items/{itemid}/uploadSubmit
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmit" }
#
#UploadInputProvSubmitAccepted:
#    pattern:  /{id}/items/{itemid}/uploadSubmitAccepted
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmitAccepted" }
#
#UploadInputProvSubmitCanceled:
#    pattern:  /{id}/items/{itemid}/uploadSubmitCanceled
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmitCanceled" }
#
##inputs--------------------
#ManageInputsProv:
#    pattern:  /{id}/inputs
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageInputsProv" }
#
##removed-------------------
#MasterProvRemoved:
#    pattern:  /{id}/removed
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:MasterProvRemoved" }
#
##info----------------------
#EditAccountProv:
#    pattern:  /{id}/Info
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditAccountProv" }
#
##entity--------------------
#MasterProvEntiti:
#    pattern:  /{id}/entity
#    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:MasterProvEntiti" }
