hello_di_master_retailer_index:
    pattern:  /
    defaults: { _controller: "HelloDiMasterBundle:Retailer:index"}

#transaction
hello_di_master_retailer_transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: "HelloDiMasterBundle:Retailer:transaction"}

#items
hello_di_master_retailer_item:
    pattern:  /{id}/items
    defaults: { _controller: "HelloDiMasterBundle:Retailer:item" }

#users
hello_di_master_retailer_user:
    pattern:  /{id}/users
    defaults: { _controller: "HelloDiMasterBundle:Retailer:user" }

hello_di_master_retailer_user_add:
    pattern:  /{id}/users/add
    defaults: { _controller: "HelloDiMasterBundle:Retailer:userAdd" }

hello_di_master_retailer_user_edit:
    pattern:  /{id}/users/{user_id}/edit
    defaults: { _controller: "HelloDiMasterBundle:Retailer:userEdit" }

#info
hello_di_master_retailer_info:
    pattern:  /{id}/info
    defaults: { _controller: "HelloDiMasterBundle:Retailer:info" }

#entity
hello_di_master_retailer_entity:
    pattern:  /{id}/entity
    defaults: { _controller: "HelloDiMasterBundle:Retailer:entity" }