hello_di_master_homepage:
    pattern:  /
    defaults: { _controller: HelloDiMasterBundle:Default:dashboard }

hello_di_master_provider:
    resource: "@HelloDiMasterBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

hello_di_master_operator:
    resource: "@HelloDiMasterBundle/Resources/config/routing/operator.yml"
    prefix:   /operator