hello_di_master_homepage:
    pattern:  /
    defaults: { _controller: HelloDiMasterBundle:Default:dashboard }

hello_di_master_provider:
    resource: "@HelloDiMasterBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

hello_di_master_distributor:
    resource: "@HelloDiMasterBundle/Resources/config/routing/distributor.yml"
    prefix:   /distributor

hello_di_master_retailer:
    resource: "@HelloDiMasterBundle/Resources/config/routing/retailer.yml"
    prefix:   /distributor/{id}/retailer

hello_di_master_operator:
    resource: "@HelloDiMasterBundle/Resources/config/routing/operator.yml"
    prefix:   /operator

hello_di_master_item:
    resource: "@HelloDiMasterBundle/Resources/config/routing/item.yml"
    prefix:   /item

hello_di_master_code:
    resource: "@HelloDiMasterBundle/Resources/config/routing/code.yml"
    prefix:   /code

hello_di_master_entity:
    resource: "@HelloDiMasterBundle/Resources/config/routing/entity.yml"
    prefix:   /entity

hello_di_master_setting:
    resource: "@HelloDiMasterBundle/Resources/config/routing/setting.yml"
    prefix:   /setting