parameters:
#    hello_di_master.example.class: HelloDi\MasterBundle\Example

services:
#    hello_di_master.example:
#        class: %hello_di_master.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
