hello_di_pricing_model:
    resource: "@HelloDiPricingBundle/Resources/config/routing/model.yml"
    prefix:  /model

hello_di_pricing_provider_model:
    resource: "@HelloDiPricingBundle/Resources/config/routing/providerModel.yml"
    prefix:  /app/m/provider/model

hello_di_pricing_distributor_item:
    resource: "@HelloDiPricingBundle/Resources/config/routing/distributorPricing.yml"
    prefix:  /app/m/distributor/{id}/items
