app_master:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/master.yml"
    prefix:   /app/m

app_Distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/distributors.yml"
    prefix:   /app/d

app_Retailers:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/retailers.yml"
    prefix:   /app/r


hellodi_homepage:
    path: /{locale}
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:index,locale:en}
    requirements:
        locale: en|fr|de

transactions_ogone_template:
    path:   /ogone-template
    defaults:
        _controller: FrameworkBundle:Template:template
        template: HelloDiDiDistributorsBundle:Ogone:EpaymentTemplate.html.twig

item_add_temp:
    path: /temp/item_add_prov
    defaults: { _controller: HelloDiDiDistributorsBundle:temp:itemAdd}

item_add_dist:
    path: /temp/item_add_dist/{distId}
    defaults: { _controller: HelloDiDiDistributorsBundle:temp:addIMTUItemsToDist}

item_add_ret:
    path: /temp/item_add_ret/{RetId}
    defaults: { _controller: HelloDiDiDistributorsBundle:temp:addIMTUItemsDistToRet}