layout:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:index }

app_master:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/master.yml"
    prefix:   /app/master

app_Distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/distributors.yml"
    prefix:   /app/distributors

app_Retailers:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/retailers.yml"
    prefix:   /app/retailers

