layout:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:index }

app_master:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/master.yml"
    prefix:   /app/m

app_Distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/distributors.yml"
    prefix:   /app/d

app_Retailers:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/retailers.yml"
    prefix:   /app/r

pdf:
    pattern:  /pdf
    defaults: { _controller: HelloDiDiDistributorsBundle:Account:pdf}

test:
    pattern:  /{id}/test
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:test1}

transactions_ogone_template:
    path:   /ogone-template
    defaults:
        _controller: FrameworkBundle:Template:template
        template: HelloDiDiDistributorsBundle:Ogone:EpaymentTemplate.html.twig
