app_master:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/master.yml"

app_Distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/distributors.yml"

app_Retailers:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/retailers.yml"

transactions_ogone_template:
    path:   /ogone-template
    defaults:
        _controller: FrameworkBundle:Template:template
        template: HelloDiDiDistributorsBundle:Ogone:EpaymentTemplate.html.twig

item_add_temp:
    path: /temp/item_add_prov
    defaults: { _controller: HelloDiDiDistributorsBundle:temp:itemAdd}

item_add_dist:
    path: /temp/item_add_dist/{distId}
    defaults: { _controller: HelloDiDiDistributorsBundle:temp:addIMTUItemsToDist}

item_add_ret:
    path: /temp/item_add_ret/{RetId}
    defaults: { _controller: HelloDiDiDistributorsBundle:temp:addIMTUItemsDistToRet}