layout:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:index }
app:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/app.yml"
    prefix:   /app

