layout:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:index }

app_master:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/master.yml"
    prefix:   /app/m

app_Distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/distributors.yml"
    prefix:   /app/d

app_Retailers:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/retailers.yml"
    prefix:   /app/r

pdf:
    pattern:  /pdf
    defaults: { _controller: HelloDiDiDistributorsBundle:Account:pdf}

ogonetest:
    pattern:  /ogonetest
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:OgoneTestAccept }

ogonetestaccept:
    pattern:  /ogonetest/accept
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:OgoneTestAccept }
