layout:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:index }

app_master:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/master.yml"
    prefix:   /app/m

app_Distributors:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/distributors.yml"
    prefix:   /app/d

app_Retailers:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/retailers.yml"
    prefix:   /app/r


homepage_about:
    path: /about
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:About}

homepage_contact:
    path: /contact
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:Contact}


homepage_news:
    path: /news
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:News}


homepage_product:
    path: /product
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:Product}


homepage_services:
    path: /services
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:Services}

homepage_network:
    path: /network
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:Network}

homepage_language:
    path: /language/{locale}
    defaults: { _controller: HelloDiDiDistributorsBundle:HomePage:language}
    requirements:
        locale: en|fr|de

transactions_ogone_template:
    path:   /ogone-template
    defaults:
        _controller: FrameworkBundle:Template:template
        template: HelloDiDiDistributorsBundle:Ogone:EpaymentTemplate.html.twig
