parameters:
#    hello_di_di_distributors.example.class: HelloDi\DiDistributorsBundle\Example

#services:
#    hello_di_di_distributors.example:
#        class: %hello_di_di_distributors.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    hello_di_di_distributors.registration.form.type:
        class: HelloDi\DiDistributorsBundle\Form\User\UserRegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: UserRegistration }

    hello_di_di_distributors.profile.form.type:
        class: HelloDi\DiDistributorsBundle\Form\User\UserProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: UserProfile }

    hello_di_di_distributors.event_listener.locale_listener:
        class: HelloDi\DiDistributorsBundle\Listener\LocaleListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    hello_di_di_distributors.event_listener.login:
        class: HelloDi\DiDistributorsBundle\Listener\SecurityListener
        arguments: [@security.context,@session]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin}

    hello_di_di_distributors.form.handler.registration:
        class: HelloDi\DiDistributorsBundle\Form\Handler\RegistrationFormHandler
        arguments: [@fos_user.registration.form, @request, @fos_user.user_manager, @fos_user.mailer, @fos_user.util.token_generator ,@security.context]
        scope: request
        public: false

    authentication_handler:
        class: HelloDi\DiDistributorsBundle\Listener\AuthenticationHandler
        arguments: [@router, @security.context]

    hello_di_di_distributors.balancechecker:
        class: HelloDi\DiDistributorsBundle\Listener\BalanceChecker
        arguments: [@session]

    hello_di_di_distributors.codeselector:
            class: HelloDi\DiDistributorsBundle\Listener\CodeSelector
            arguments: [@doctrine.orm.default_entity_manager,@hello_di_di_distributors.balancechecker]

    hello_di_di_distributors.Tickets:
        class: HelloDi\DiDistributorsBundle\Listener\Taketickets
        arguments: [@doctrine.orm.default_entity_manager]

    hello_di_di_distributors.ogone.client:
        class:  HelloDi\DiDistributorsBundle\Ogone\Client
        arguments: [@router,@doctrine.orm.default_entity_manager,%ogone_pspid%, %ogone_sha_in%, %ogone_sha_out%, %ogone_submit_url%, %locale%]

    acme.twig.extension.loader:
        class:        Twig_Extension_StringLoader
        tags:
         - { name: 'twig.extension' }