parameters:
#    hello_di_di_distributors.example.class: HelloDi\DiDistributorsBundle\Example

#services:
#    hello_di_di_distributors.example:
#        class: %hello_di_di_distributors.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    hello_di_di_distributors.form.handler.registration:
        class: HelloDi\DiDistributorsBundle\Form\Handler\RegistrationFormHandler
        arguments: [@fos_user.registration.form, @request, @fos_user.user_manager, @fos_user.mailer, @fos_user.util.token_generator ,@security.context]
        scope: request
        public: false

    hello_di_di_distributors.balancechecker:
        class: HelloDi\DiDistributorsBundle\Listener\BalanceChecker
        arguments: [@session,@translator.default]

    hello_di_di_distributors.codeselector:
            class: HelloDi\DiDistributorsBundle\Listener\CodeSelector
            arguments: [@session,@doctrine.orm.default_entity_manager,@hello_di_di_distributors.balancechecker]

    hello_di_di_distributors.Tickets:
        class: HelloDi\DiDistributorsBundle\Listener\Taketickets
        arguments: [@doctrine.orm.default_entity_manager]

    hello_di_di_distributors.ogone.client:
        class:  HelloDi\DiDistributorsBundle\Ogone\Client
        arguments: [@router, @doctrine.orm.default_entity_manager, %ogone_pspid%, %ogone_sha_in%, %ogone_sha_out%, %ogone_submit_url%,@hello_di_di_distributors.ogone.routescontainer]
        scope: request

    hello_di_di_distributors.ogone.routescontainer:
        class:  HelloDi\DiDistributorsBundle\Ogone\RoutesContainer
        arguments: [@request]
        scope: request

    hello_di_di_distributors.twig.extension.loader:
        class:        Twig_Extension_StringLoader
        tags:
         - { name: 'twig.extension' }

    CalcVatFormula:
        class: HelloDi\DiDistributorsBundle\Listener\CalcVatFormula
        arguments: [%VatFormula%]
