#HelloDi\DiDistributorsBundle\Entity\Entiti:
#    properties:
#        entName:
#            - NotBlank:
#                message: "entity.entname.not_blank"
#            - Length:
#                min: 5
#                max: 10
#                minMessage: 'this.field.should.not.less.of.3'
#                maxMessage: 'this.field.should.not.more.of.10'
#        entVatNumber:
#            - NotBlank:
#                message: "entity.entvatnumber.not_blank"
#            - Length:
#                min: 3
#                max: 10
#                minMessage: 'this.field.should.not.less.of.3'
#                maxMessage: 'this.field.should.not.more.of.10'
#        entWebsite:
#            - NotBlank:
#                message: "entity.entname.not_blank"
#            - Url:
#                message: "entity.url.notmatch"


HelloDi\DiDistributorsBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: usernameCanonical
            errorPath: username
            message: 'fos_user.username.already_used'

        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: emailCanonical
            errorPath: email
            message: 'fos_user.email.already_used'

HelloDi\DiDistributorsBundle\Entity\Account:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: accName
            message: 'fos_user.accName.already_used'
