FOS\UserBundle\Form\Model\ChangePassword:

    properties:
        new:
            - Length:
                min: 6
                max: 25
                minMessage: "password_must_be_at_least_{{limit}}_characters_length"
                maxMessage: "pasword_name_cannot_be_longer_than_{{limit}}_characters_length"

HelloDi\DiDistributorsBundle\Entity\Entiti:
    properties:
        entVatNumber:
            - Regex:
                pattern: "/\d/"
                match: true
                message: 'Only_numbers_are_accepted'

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: entName
            message: 'This_entity_name_is_already_in_use'

HelloDi\DiDistributorsBundle\Entity\Tax:
    properties:
        tax:
            - Regex:
                pattern: "/^\d/"
                match:   true
                message: 'Only_numbers_are_accepted'


HelloDi\DiDistributorsBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: usernameCanonical
            errorPath: username
            message: 'This_username_is_already_in_use'

    properties:
        plainPassword:
            - Length:
                min: 6
                max: 25
                minMessage: "password_must_be_at_least_{{limit}}_characters_length"
                maxMessage: "pasword_name_cannot_be_longer_than_{{limit}}_characters_length"

HelloDi\DiDistributorsBundle\Entity\Account:
    properties:
        accTerms:
            - Regex:
                pattern: "/\d/"
                match:   true
                message: 'Only_numbers_are_accepted'
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: accName
            message: 'This_account_name_is_already_in_use'

HelloDi\DiDistributorsBundle\Entity\Transaction:
        Fees:
            - Regex:
                pattern: "/\d/"
                match:   true
                message: 'Only_numbers_are_accepted'

#mostafa
#HelloDi\DiDistributorsBundle\Entity\ItemDesc:
#    properties:
#        descdesc:
#            - NotBlank: ~
#            - Regex:
#                pattern: "/{{pin}}/"
#                match:   true
#                message: 'pin_not_exist'
#            - Regex:
#                pattern: "/{{serial}}/"
#                match:   true
#                message: 'sn_not_exist'
#            - Regex:
#                pattern: "/{{expire}}/"
#                match:   true
#                message: 'expiry_not_exist'
#            - Regex:
#                pattern: "/{{printdate}}/"
#                match:   true
#                message: 'printdate_not_exist'
#            - Regex:
#                pattern: "/{{duplicate}}/"
#                match:   true
#                message: 'duplicate_not_exist'

HelloDi\DiDistributorsBundle\Entity\Item:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: itemCode
            message: 'This_item_code_exist_already'

HelloDi\DiDistributorsBundle\Entity\Operator:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            message: 'This_operator_name_exist_already'

#mostafa
