HelloDi\DiDistributorsBundle\Entity\Entiti:
    properties:
        entVatNumber:
            - Regex:
                pattern: "/\d/"
                match: true
                message: 'Only_numbers_are_accepted'

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: entName
            message: 'This_entity_name_is_already_in_use'
HelloDi\DiDistributorsBundle\Entity\Tax:
    properties:
        tax:
            - Regex:
                pattern: "/^\d/"
                match:   true
                message: 'Only_numbers_are_accepted'


HelloDi\DiDistributorsBundle\Entity\User:

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: usernameCanonical
            errorPath: username
            message: 'This_username_is_already_in_use'

    properties:
        plainPassword:
            - Length:
                min: 6
                max: 25
                minMessage: "password must be at least {{ limit }} characters length"
                maxMessage: "pasword name cannot be longer than {{ limit }} characters length"


HelloDi\DiDistributorsBundle\Entity\Account:
    properties:
        accTerms:
            - Regex:
                pattern: "/\d/"
                match:   true
                message: 'Only_numbers_are_accepted'
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: accName
            message: 'This_account_name_is_already_in_use'

HelloDi\DiDistributorsBundle\Entity\Transaction:
        Fees:
            - Regex:
                pattern: "/\d/"
                match:   true
                message: 'Only_numbers_are_accepted'





#mostafa
HelloDi\DiDistributorsBundle\Entity\ItemDesc:
    properties:
        descdesc:
            - NotBlank: ~
            - Regex:
                pattern: "/{{pin}}/"
                match:   true
                message: pin not exist in description.
            - Regex:
                pattern: "/{{serial}}/"
                match:   true
                message: serial not exist in description.
#mostafa
