HelloDi\DiDistributorsBundle\Entity\Entiti:
    properties:
        entVatNumber:
            - Regex:
                pattern: "/\d/"
                match: true
                message: 'only numeric'

HelloDi\DiDistributorsBundle\Entity\Tax:
    properties:
        tax:
            - Regex:
                pattern: "/\d/"
                match:   true
                message: Your name cannot contain a number
HelloDi\DiDistributorsBundle\Entity\User:
    properties:
        firstName:
            - Regex:
                pattern: "/\d/"
                match:   false
                message: Your name cannot contain a number
        mobile:
            - Regex:
                pattern: "/\d/"
                match: true
                message: 'only numeric'

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: usernameCanonical
            errorPath: username
            message: 'fos_user.username.already_used'


HelloDi\DiDistributorsBundle\Entity\Account:
    properties:
        accTerms:
            - Regex:
                pattern: "/\d/"
                match:   true
                message: only numeric

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: accName
            message: 'this name already used'




#mostafa
HelloDi\DiDistributorsBundle\Entity\ItemDesc:
    properties:
        descdesc:
            - NotBlank: ~
            - Regex:
                pattern: "/{{pin}}/"
                match:   true
                message: pin not exist in description.
            - Regex:
                pattern: "/{{serial}}/"
                match:   true
                message: serial not exist in description.
#mostafa
