ShowMyAccount:
    pattern:  /providers
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ShowMyAccount" }

ManageProv:
    pattern:  /providers/manageprov/{id}/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageProv" }

EditAccountProv:
    pattern:  /providers/info
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditAccountProv" }

EditAccountProvSubmit:
    pattern:  /providers/manageprovsubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditAccountProvSubmit" }

ManageProvEntiti:
    pattern:  /providers/entiti
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageProvEntiti" }

AddAccountProvMaster:
    pattern:  /providers/new_provider/entity
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountProvMaster" }

AddAccountProvMasterOk:
    pattern:  /providers/Master/new_provider/account/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountProvMasterOk" }

AddAccountProveMaster2Step:
    pattern:  /providers/new_provider
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountProveMaster2Step" }

ChangeAdminProvAccountOk:
    pattern:  /providers/{iduser}/{idacc}/change/userprivilegeprovok
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ChangeAdminProvAccountOk" }

#-------------------

ShowMyAccountDist:
    pattern:  /distributors/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ShowMyAccountDist" }

AddAccountDistMaster:
    pattern:  /distributors/add/accountdist
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddAccountDistMaster" }

ManageDist:
    pattern:  /distributors/managedist/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDist" }

ManageDistInfo:
    pattern:  /distributors/info
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistInfo" }

ManageDistInfoEdit:
    pattern:  /distributors/managedistinfo/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistInfoEdit" }

ManageDistTransaction:
    pattern:  /distributors/sub_accounts1
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistTransaction" }

ManageDistChildren:
    pattern:  /distributors/sub_accounts/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistChildren"}
DistChildrenCreate:
    pattern:  /distributors/managedistchildren/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistChildren"}
ManageDistUser:
    pattern:  /distributors/user/
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistUser" }
ManageDistUserSearch:
    pattern:  /distributors/search/managedistuser/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistUserSearch" }
DistUserPrivilege:
    pattern:  /account/{idacc}/user/{iduser}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:DistUserPrivilege" }
ManageDistUserSearchReset:
    pattern:  /reset/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistUserSearchReset" }
AccountDistChildrenSearch:
    pattern:  /distributors/{id}/SearchDistChildren
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AccountDistChildrenSearch"}
ManageDistSettings:
    pattern:  /distributors/settings
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistSettings"}
ManageDistSettingsSubmit:
    pattern:  /distributors/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageDistSettingsSubmit"}
#---- items prov
ManageItemsProv:
    pattern:  /providers/items
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageItemsProv" }

AddItemProv:
    pattern:  /providers/items/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemProv" }

AddItemProvSubmit:
    pattern:  /providers/items/addsubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemProvSubmit" }

EditItemProv:
    pattern:  /providers/items/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemProv" }

EditItemProvSubmit:
    pattern:  /providers/items/editsubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemProvSubmit" }

#---- items dist
ManageItemsDist:
    pattern:  /distributors/items
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageItemsDist" }

AddItemDist:
    pattern:  /distributors/items/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemDist" }

AddItemDistSubmit:
    pattern:  /distributors/items/addSubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:AddItemDistSubmit" }

EditItemDist:
    pattern:  /distributors/items/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemDist" }

EditItemDistSubmit:
    pattern:  /distributors/items/editsubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:EditItemDistSubmit" }

#---- inputs prov
ManageInputsProv:
    pattern:  /providers/inputs
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:ManageInputsProv" }

UploadInputProv:
    pattern:  /providers/inputs/upload
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProv" }

UploadInputProvSubmit:
    pattern:  /providers/inputs/uploadsubmit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmit" }

UploadInputProvSubmitAccepted:
    pattern:  /providers/inputs/uploadsubmitaccepted
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmitAccepted" }

UploadInputProvSubmitCanceled:
    pattern:  /providers/inputs/uploadsubmitcanceled
    defaults: { _controller: "HelloDiDiDistributorsBundle:Account:UploadInputProvSubmitCanceled" }
#-------Retailers--------------#
ListUsersInRetailers:
    pattern:  /retailers/{id}/users
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:ListUsersInRetailers" }