distributors_dashboard:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:dashboard}

distributors_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/account.yml"
    prefix:   admin/account-setting

distributors_retailer:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/retailer.yml"
    prefix:   /retailers

distributors_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/items.yml"
    prefix:   /admin/items
distributors_reports:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/reports.yml"
    prefix:   /reports
