distributors_dashboard:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:dashboard}

distributors_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/account.yml"
    prefix:   /admin/account-settings

distributors_transaction:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/transaction.yml"
    prefix:   /transactions

distributors_ogone_transaction:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Ogone/dist_recharge.yml"
    prefix:   admin/transactions

distributors_retailer:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/retailer.yml"
    prefix:   /retailers

distributors_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/items.yml"
    prefix:   /items

distributors_reports:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/reports.yml"
    prefix:   /reports

distributors_tickets:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/tickets.yml"
    prefix:   /tickets

distributors_notification:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Distributors/notification.yml"
    prefix:   /notification

distCheckItemCurrEqAccCurr:
    pattern:  /CheckItemCurrEqAccCurr
    defaults: { _controller: HelloDiDiDistributorsBundle:Account:CheckItemCurrEqAccCurr }