Ent_Main:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ListEntities" }

Ent_Index:
    pattern:  /index/{id}
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:index" }

Ent_Accounts:
    pattern:  /accounts
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:accounts" }

Ent_Users:
    pattern:  /users
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:users" }

Ent_Info:
    pattern:  /info
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:info" }

Ent_InfoSubmit:
    pattern:  /entities/info/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:infoSubmit" }
AddNewUserEntiti:
    pattern:  /entities/{id}/user/add
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:AddNewUserEntiti" }
ModifyUserPrivilege:
    pattern:  /entities/{idacc}/user/{iduser}/edit
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ModifyUserPrivilege" }
AddProv:
    pattern:  /entities/{id}/accounts/new-provoder
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:AddProv"}
AddDist:
    pattern:  /entities/{id}/accounts/new-distibutors
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:AddDist"}
ProvTransaction:
    pattern:  /provider/{}/transaction
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ProvTransaction"}
DistTransaction:
    pattern:  /distributors/{}/transaction
    defaults: { _controller: "HelloDiDiDistributorsBundle:Entiti:ProvTransaction"}