item:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:index" }

item_new:
    pattern:  /new
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:new" }

item_edit:
    pattern:  /details
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:edit" }

item_update:
    pattern:  /{id}/update
    defaults: { _controller: "HelloDiDiDistributorsBundle:Item:update" }
    requirements: { _method: post|put }
