loginsuccess:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:dashboard }

master_entities:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/entities.yml"
    prefix:   /entities

master_dist:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/distributors.yml"
    prefix:   /distributors

master_prov:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/providers.yml"
    prefix:   /providers

master_retailer:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/retailer.yml"
    prefix:   /distributors/{distid}/retailers

master_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/item.yml"
    prefix:   /items

master_operators:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/operator.yml"
    prefix:   /operators

master_codes:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/code.yml"
    prefix:   /codes

master_settings:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/setting.yml"
    prefix:   /admin/settings

master_print:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/print.yml"
    prefix:   /print

master_tickets:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/tickets.yml"
    prefix:   /tickets

master_notifications:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/notification.yml"
    prefix:   /notifications

master_profile:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/profile.yml"
    prefix:   /admin/profile

master_tax:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/tax.yml"
    prefix:   /tax

master_exceptions:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/exceptions.yml"
    prefix:   /exceptions


master_log:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/log.yml"
    prefix:   /logs

test_index:
    pattern:  /test
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:index }

test1_index:
    pattern:  /test1/{id}
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:index1, id: 0 }

testlistlang:
    pattern:  /listlang
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:listlangs }