loginsuccess:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:dashboard }

master_entities:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/entities.yml"
    prefix:   /entities

master_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/accounts.yml"
    prefix:   /accounts

master_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/item.yml"
    prefix:   /items

master_codes:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/code.yml"
    prefix:   /codes