loginsuccess:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Default:dashboard }

master_entities:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/entities.yml"
    prefix:   /entities

master_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/accounts.yml"
    prefix:   /accounts

master_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/item.yml"
    prefix:   /items

master_operators:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/operator.yml"
    prefix:   /operators

master_codes:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/code.yml"
    prefix:   /codes

master_settings:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/setting.yml"
    prefix:   /settings

master_print:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/print.yml"
    prefix:   /print

master_tickets:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Master/tickets.yml"
    prefix:   /tickets

test_index:
    pattern:  /test
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:index }

test1_index:
    pattern:  /test1/{id}
    defaults: { _controller: HelloDiDiDistributorsBundle:Test:index1, id: 0 }