retailers_dashboard:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:dashboard}

ritailers_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/account.yml"
    prefix:   /admin/account-setting

RetailerTransaction:
    pattern:  /transaction/history
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Transaction}

RetailerDetailsTransaction:
    pattern:  /transaction/history/{id}/details
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:DetailsTransaction}

RetailerSale:
    pattern:  /report/sale
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Sale}

retailer_shop:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/account.yml"
    prefix:   /shop

retailer_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/items.yml"
    prefix:   /items