retailers_dashboard:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:dashboard}

ritailers_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/setting.yml"
    prefix:   /admin/account-setting

retailer_report:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/report.yml"
    prefix:   /report

retailer_transaction:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/report.yml"
    prefix:   /report

retailer_transaction:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/transaction.yml"
    prefix:   /transaction

retailer_ticket:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/tickets.yml"
    prefix:   /tickets

retailer_shop:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/shop.yml"
    prefix:   /shop

retailer_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/items.yml"
    prefix:   /items

# ---- Ogone Start ---- #
retailer_OgoneTransactions:
    pattern:  /transactions/new
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:new }

retailer_OgoneTransactions_validate:
    pattern:  /transactions/{id}/validate
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:Validate }

retailer_OgoneTransactions_Accept:
    pattern:  /transactions/accept
    defaults: { _controller: HelloDiDiDistributorsBundle:Epayment:Accept }

# ---- Ogone End ---- #