retailers_dashboard:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:dashboard}

ritailers_account:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/account.yml"
    prefix:   /admin/account-setting

RetailerTransaction:
    pattern:  /transaction/history
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Transaction}

RetailerDetailsTransaction:
    pattern:  /transaction/history/{id}/details
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:DetailsTransaction}

RetailerSale:
    pattern:  /report/sale
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:Sale}


RetailerTickets:
    pattern:  /tickets
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:tickets }

RetailerTicketsNote:
    pattern:  /tickets/{id}/notes
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsnote }

RetailerTicketsClose:
    pattern:  /tickets/{id}/close
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsclose }

RetailerTicketsNew:
    pattern:  /tickets/new
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsnew }

RetailerTicketsChangeStatus:
    pattern:  /{id}/change/status
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketschangestatus }

RetailerTicketsStatus:
    pattern:  /{id}/change/
    defaults: { _controller: HelloDiDiDistributorsBundle:Retailers:ticketsstatus }


retailer_shop:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/account.yml"
    prefix:   /shop

retailer_items:
    resource: "@HelloDiDiDistributorsBundle/Resources/config/routing/Retailers/items.yml"
    prefix:   /items