parameters:
#    hello_di_aggregator.example.class: HelloDi\AggregatorBundle\Example

services:
#    hello_di_aggregator.example:
#        class: %hello_di_aggregator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
