DistProfile:
    pattern:  /profile
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistProfile }

DistStaff:
    pattern:  /staff
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaff }

DistStaffAdd:
    pattern:  /staff/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaffAdd }

DistStaffEdit:
    pattern:  /{id}/staff/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaffEdit }

DistChangeRole:
    pattern:  /{id}/staff/ChangeRole
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistChangeRole }

DistTransaction:
    pattern:  /transaction
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistTransaction }
DistDetailsTransaction:
    pattern:  /transaction/{id}/details
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DetailsTransaction }

DistLoadActionOwn:
    pattern:  /transaction/loadd
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistLoadActionOwn }

DistLoadActionRetailer:
    pattern:  /transaction/loadr
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistLoadActionRetailer }