DistProfile:
    pattern:  /profile
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistProfile }

DistStaff:
    pattern:  /staff
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaff }

DistStaffAdd:
    pattern:  /staff/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaffAdd }

DistStaffEdit:
    pattern:  /staff/{id}/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaffEdit }
