Profile:
    pattern:  /{id}/profile
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:Profile,id:2 }

Staff:
    pattern:  /{id}/staff
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:Staff,id:10 }

StaffAdd:
    pattern:  /{id}/staff/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:StaffAdd }

StaffEdit:
    pattern:  /{id}/staff/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:StaffEdit }

ChangeRole:
    pattern:  /{id}/staff/ChangeRole
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ChangeRole }
