DistProfile:
    pattern:  /profile
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistProfile }

DistStaff:
    pattern:  /staff
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaff }

DistStaffAdd:
    pattern:  /{id}/staff/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaffAdd }

DistStaffEdit:
    pattern:  /{id}/staff/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistStaffEdit }

DistChangeRole:
    pattern:  /{id}/staff/ChangeRole
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistChangeRole }
