items_show:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ShowItems }

items_item_per_retailers:
    pattern:  /{id}/item_per_retailers
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ItemPerRetailer }