items_show:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ShowItems }

items_item_per_retailers:
    pattern:  /{itemid}/item-per-retailers
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ItemPerRetailer }