DistShowNotification:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ShowNotification }

DistReadNotification:
    pattern:  /read
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ReadNotification }