DistSale:
    pattern:  /sales
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:Sale }
DistDetailsSale:
    pattern:  /Details/{id}/sales
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DetailsSale }