retailer_show:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:ShowRetaierAccount" }

DistRetailerUser:
    pattern:  /{id}/users
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUser }

DistRetailerUserEdit:
    pattern:  /{id}/users/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserEdit }

DistRetailerUserAdd:
    pattern:  /{id}/users/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserAdd }

DistRetailerUserChangeRole:
    pattern:  /{id}/users/changerole
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserChangeRole }

DistNewRetailer:
    pattern:  /new
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistNewRetailer }

DistRetailerSetting:
    pattern:  /{id}/settings
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerSetting }

Retailer_Transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailersTransaction }

Retailer_details:
    pattern:  /{id}/details
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:Details }

Retailer_edit:
    pattern:  /{id}/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:editRetailers }

#start

DistRetailerFunding:
    pattern:  /{id}/transaction/transfer
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:Funding"}

DistRetailerTransferFunding:
    pattern:  /{id}/transaction/transfer/transfer
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:FundingTransfer"}

DistRetailerUpdateFunding:
    pattern:  /{id}/transaction/transfer/update
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:FundingUpdate"}

#end

#item
dist_RetailerItem:
    pattern:  /{id}/items
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailerItems }

dist_RetailerItemAdd:
    pattern:  /{id}/items/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailerItemsAdd }

dist_RetailerItemEdit:
    pattern:  /{id}/items/{priceid}/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailerItemsEdit }
