retailer_show:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:ShowRetaierAccount" }

DistRetailerUser:
    pattern:  /{id}/users
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUser }

DistRetailerUserEdit:
    pattern:  /{id}/users/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserEdit }

DistRetailerUserAdd:
    pattern:  /{id}/users/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserAdd }

DistRetailerUserChangeRole:
    pattern:  /{id}/users/changerole
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserChangeRole }

DistNewRetailer:
    pattern:  /new
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistNewRetailer }

DistRetailer:
    pattern:  /new
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistNewRetailer }


Retailer_Transaction:
    pattern:  /{id}/transactions
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailersTransaction }

Retailer_details:
    pattern:  /{id}/details
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:Details }

Retailer_edit:
    pattern:  /{id}/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:editRetailers }

#item
dist_RetailerItem:
    pattern:  /{id}/items
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailerItems }