retailer_show:
    pattern:  /
    defaults: { _controller: "HelloDiDiDistributorsBundle:Distributors:ShowRetaierAccount" }

DistRetailerUser:
    pattern:  /{id}/users
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUser }

DistRetailerUserEdit:
    pattern:  /{id}/users/edit
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserEdit }

DistRetailerUserAdd:
    pattern:  /{id}/users/add
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserAdd }

DistRetailerUserChangeRole:
    pattern:  /{id}/users/changerole
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerUserChangeRole }

DistNewRetailer:
    pattern:  /NewRetailer
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistNewRetailer }

DistRetailerSetting:
    pattern:  /{id}/settings
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:DistRetailerSetting }

#item
dist_RetailerItem:
    pattern:  /{id}/items
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:RetailerItems }