DistTickets:
    pattern:  /
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:tickets }

DistTicketsNote:
    pattern:  /{id}/notes
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ticketsnote }

DistTicketsNew:
    pattern:  /new/{data}/
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:tickestnew,data:null }

DistTicketsChangeStatus:
    pattern:  /{id}/changestatus
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ticketschangestatus }

DistTicketsStatus:
    pattern:  /{id}/change
    defaults: { _controller: HelloDiDiDistributorsBundle:Distributors:ticketsstatus }
