parameters:
#    hello_di_distributor.example.class: HelloDi\DistributorBundle\Example

services:
#    hello_di_distributor.example:
#        class: %hello_di_distributor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
